# Generated by Django 5.2.8 on 2025-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe History',
                'verbose_name_plural': 'Recipe History',
                'db_table': 'recipe_history',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
