# Generated by Django 5.2.8 on 2025-12-04 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipehistory',
            index=models.Index(fields=['user', '-viewed_at'], name='recipe_hist_user_id_9fceb3_idx'),
        ),
    ]
