# Generated by Django 5.2.8 on 2025-12-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, help_text='in grams', max_digits=8)),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0.0, help_text='in grams', max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, default=0.0, help_text='in grams', max_digits=8)),
                ('fiber', models.DecimalField(decimal_places=2, default=0.0, help_text='in grams', max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=2, default=0.0, help_text='in grams', max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=2, default=0.0, help_text='in milligrams', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nutrition',
                'verbose_name_plural': 'Nutrition',
                'db_table': 'nutrition',
            },
        ),
        migrations.CreateModel(
            name='IngredientNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('carbohydrates_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('sugar_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('sodium_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='ingredients.ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient Nutrition',
                'verbose_name_plural': 'Ingredient Nutrition',
                'db_table': 'ingredient_nutrition',
            },
        ),
    ]
