# Generated by Django 5.2.8 on 2025-12-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/')),
                ('unit', models.CharField(default='g', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientSubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitution_ratio', models.CharField(blank=True, help_text="e.g., '1:1' or '1 cup:1 cup'", max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='ingredients.ingredient')),
                ('substitute_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_in', to='ingredients.ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient Substitute',
                'verbose_name_plural': 'Ingredient Substitutes',
                'db_table': 'ingredient_substitutes',
                'unique_together': {('original_ingredient', 'substitute_ingredient')},
            },
        ),
    ]
